#!/bin/bash

ShowTodo=true;

for PARAMS in "$@" ; do

    if [ "$PARAMS" == "clean" ] ; then
        if [ -d build/ ]; then
            rm -rf build/
        fi
    fi
    
    if [ "$PARAMS" == "open" ] ; then
       OPEN=true;
    fi
    
    if [ "$PARAMS" == "mute" ] ; then
        ShowTodo=false;
    fi
    
done


make -f MakeExamples html 2>&1  | \
grep -v "reading sources..." | \
# grep -v "isn't included" | \
grep -v "copying images..." | \
grep -v "writing output..." | \
# grep -v "verilog/src/unisims" --line-buffered | \
GREP_COLORS='mt=01;91' grep  -ie "error\w*\|fatal\w*\|failed\w*"   -e '^' --color=always --line-buffered |\
GREP_COLORS='mt=01;93' grep  -ie "warn\w*\|SEVERE\w*" -e '^' --color=always --line-buffered |\
GREP_COLORS='mt=01;96' grep  -ie "build\w*" -e '^' --color=always --line-buffered |\
GREP_COLORS='mt=01;32' grep  -ie "succeed\w*\|done\w*" -e '^' --color=always --line-buffered ;
if [ $OPEN ]; then
    xdg-open build/html/index.html
fi

TEXT="$(./getTODO.sh)"

echo "ShowTodo = $ShowTodo"

if [ "$ShowTodo" == "true" ]; then
    zenity --info \
    --text="$TEXT"
fi
